import { ResponseModel } from './../shared-model';

export interface UserResponseModel extends ResponseModel {
    data: UserModel
}

// Generated by https://quicktype.io

export interface UserModel {
    id:                         string;
    email:                      string;
    firstName:                  string;
    lastName:                   string;
    profileImageUrl:            null;
    address:                    null;
    alpha2CountryCode:          null;
    state:                      null;
    phoneNumber:                null;
    city:                       null;
    scope:                      string;
    preferredProfileType:       string;
    businessName:               null;
    businessAddress:            null;
    businessEmail:              null;
    businessPhone:              null;
    businessCountryCode:        null;
    businessState:              null;
    businessCity:               null;
    businessLogoUrl:            null;
    businessRegistrationNumber: null;
    isSellerApproved:           boolean;
    sellerApprovalStatus:       null;
}
