import { ResponseModel } from './../shared-model';

// Generated by https://quicktype.io

export interface EquipmentsUsageResponseModel extends ResponseModel {
    data:    EquipmentsUsage;
}

export interface EquipmentsUsage {
    equipment: Equipment;
    useage:    Useage;
}

export interface Equipment {
    id:          number;
    name:        string;
    description: string;
    isInUsed:    boolean;
    imageUrl:    string;
}

export interface Useage {
    userId:            string;
    firstName:         string;
    lastName:          string;
    name:              string;
    allocatedDateTime: string;
    roomId: string;
    creationTime: string;
}
