import { ResponseModel } from './../shared-model';

// Generated by https://quicktype.io


export interface EquipmentModel {
   name:          string;
    description:   string;
    imageUrl:      string;
    isInUsed:      boolean;
    idNo:          string;
    positionInMap: string;
    roomNo:        string;
    accessLevel:   string;
    id:            number;
    creationTime:  string;
}

export interface EquipmentsResponseModel extends ResponseModel {
    data: EquipmentModel[];
}

export interface EquipmentInputRequestModel {
    name:         string;
    description:  string;
    imageUrl:     string;
   
}
// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface AllocateEquipmentModel {
    userId:              number;
    equipmentId:         number;
    userLocation:        string;
    allocatedHoursToUse: number;
}


// Generated by https://quicktype.io

export interface AllocateEquipmentResponseModel {
    message: string;
    status:  string;
    data:    string;
}
// Generated by https://quicktype.io

export interface AllocateEquipmentFailedResponseModel {
    message: string;
    status:  string;
    data:    Data;
}

export interface Data {
    userId:            string;
    firstName:         string;
    lastName:          string;
    name:              string;
    allocatedDateTime: string;
    userLocation:      null;
}




