import { ResponseModel } from './../shared-model';

// Generated by https://quicktype.io


export interface EquipmentModel {
    name:         string;
    description:  string;
    imageUrl:     string;
    isInUsed:     boolean;
    id:           number;
    creationTime: string;
} 
export interface EquipmentsResponseModel extends ResponseModel {
    data: EquipmentModel[];
}

export interface EquipmentInputRequestModel {
    name:         string;
    description:  string;
    imageUrl:     string;
   
}
// Generated by https://quicktype.io

export interface AllocateEquipmentModel {
    userId:       string;
    equipmentId:  number;
    userLocation: string;
    roomId: string;
}

// Generated by https://quicktype.io

export interface AllocateEquipmentResponseModel {
    message: string;
    status:  string;
    data:    string;
}
// Generated by https://quicktype.io

export interface AllocateEquipmentFailedResponseModel {
    message: string;
    status:  string;
    data:    Data;
}

export interface Data {
    userId:            string;
    firstName:         string;
    lastName:          string;
    name:              string;
    allocatedDateTime: string;
    userLocation:      null;
}




