
// Generated by https://quicktype.io

export interface UserRoomResponseModel {
    message: string;
    status:  string;
    data:    UserRoom[];
}

export interface UserRoom {
    user:              User;
    room:              Room;
    hasExpired:        boolean;
    userLocation:      string;
    allocatedDateTime: string;
    creationTime: string;
    courseCode: string;
    id:                number;
}


export interface User {
    id:       number;
    idNo:     string;
    role:     string;
    userName: string;
}


// assign room request  

// Generated by https://quicktype.io

export interface AssignRoomRequestModel {
    userId:              number;
    roomId:              number;
    userLocation:        string;
    allocatedHoursToUse: number;
    courseCode:          string;
}

//assignRoomReponse 

// Generated by https://quicktype.io
export interface GetRoomSingleResponseModel {
    message: string;
    status:  string;
    data:    Room;
}
export interface GetRoomsResponseModel {
    message: string;
    status:  string;
    data:    Room[];
}
// room model
export interface Room {
    roomNo:               string;
    faculty:              string;
    capacity:             number;
    currentUsageCapacity: number;
    mapLocation:          string;
    accessLevel:          string;
    id:                   number;
    creationTime: string;
    
}
